### ISSUE TITLE
Hi i dont know coding so could you add instruction to use it?

### ISSUE THREAD

**Issue by ghost** [soruly/burstlink#6]
Hi i dont know coding so could you add instruction to use it?

**Comment by soruly** [comment]
It depends on what you want to do.

Forget about index.js which is used to generate the json file. The only useful thing here is bursklink.json. For example, given that you have MAL ID 37207 and you want to know its corresponding ID in Anilist:
```javascript
const db = await fetch("https://raw.githubusercontent.com/soruly/burstlink/master/burstlink.json").then(res => res.json());
console.log(db.find(entry => entry.mal === 37207).anilist);
```
