### ISSUE TITLE
ANN IDs are not included

### ISSUE THREAD

**Issue by LovEveRv** [soruly/burstlink#8]
Hey, this is really amazing work, but I think ANN (Anime News Network) IDs are not actually linked. But the repo description is "Link AniDB, MAL, ANN and Anilist IDs". I wonder if anything went wrong because I have a desperate need to link ANN IDs and MAL IDs. Thank you!

**Comment by soruly** [comment]
Hello. It's better to open an issue in the upstream repo which burstlink depends on: https://github.com/manami-project/anime-offline-database/

**Comment by LovEveRv** [comment]
> Hello. It's better to open an issue in the upstream repo which burstlink depends on: https://github.com/manami-project/anime-offline-database/

I've noticed that the upstream repo doesn't provide links to ANN, either. I may have to find another way to do that. Still thank you for this work! I'm gonna use it in my project.
